spring:
  application:
    name: my-app
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/localhost
    username: localhost
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework: DEBUG
